kind: PersistentVolume
apiVersion: v1
metadata:
  name: pg-pv
  namespace: solution
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"