apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dep
  Namespace: solution
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: zelfick/fastapi:latest
        ports:
        - containerPort: 80