services:
   postgres:
      image: postgres:16.2
      container_name: postgres
      restart: always
      env_file:
        - .env
      ports:
         - '5432:5432'
      volumes:
         - postgres_data:/var/lib/postgresql/data
      networks:
         - fastapipg

networks:
  fastapipg:

volumes:
   postgres_data:
    driver: local

# docker compose -f postgres.compose.yaml up -d
# verify docker ip for wsl: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' postgres
# docker compose -f postgres.compose.yaml down -v , stop and remove volumes 